[workspace]
resolver = "2"
members = [
    "crates/stellarforge-core",
    "crates/stellarforge-tx",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/xxvii-xiaxia/StellarForge"
authors = ["StellarForge Contributors"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
stellar-strkey = "0.0.18"
